import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeLead,resolveMapping,cardPayload,createOwnerLead,reportEmailPayload,verifyGoogleAddress} from '../server/owner-lead.mjs';
const schema=[{key:'owner-custom',label:'Owner',type:'person'},{key:'relatedContacts',label:'Related Contacts',type:'persons'},{key:'address',label:'Rental Property Address',type:'address'},{key:'description',label:'Notes',type:'rich-text'},{key:'stage',label:'Stage',type:'stageselect'},{key:'leadSource',label:'Source',type:'sourceselect'},{key:'trackingPhone',label:'Tracking Phone',type:'phone'},{key:'trackingEmail',label:'Tracking Email',type:'email'}];
const config={data:{fields:[{uuid:'stage',data:[{label:'NEW LEAD (M)'}]},{uuid:'leadSource',data:[{label:'Website'}]}]}};
const lead=normalizeLead({firstName:'Example',lastName:'Owner',phone:'513-555-0100',email:'test@example.com',address:'11427 Reed Hartman Hwy, Cincinnati, OH 45241',placeId:'free-analysis-place-id',formSource:'Free Rental Analysis',summary:'Property address: 11427 Reed Hartman Hwy, Cincinnati, OH 45241',pageTitle:'Free Rental Analysis | EquityTeam',pageUrl:'https://example.com/free-rental-analysis'});
test('required input validation and bounded values',()=>{assert.throws(()=>normalizeLead({}));assert.throws(()=>normalizeLead({...lead,email:'bad'}));assert.equal(normalizeLead({...lead,name:'a'.repeat(1000)}).name.length,120);});
test('free rental analysis requires contact details and a Google-selected property address',()=>{assert.throws(()=>normalizeLead({...lead,phone:''}));assert.throws(()=>normalizeLead({...lead,lastName:''}));assert.throws(()=>normalizeLead({...lead,address:''}));assert.throws(()=>normalizeLead({...lead,placeId:''}));assert.equal(lead.address,'11427 Reed Hartman Hwy, Cincinnati, OH 45241');});
test('free rental analysis replaces the browser address with Google geocoding output',async()=>{const verified=await verifyGoogleAddress(lead,{env:{GOOGLE_MAPS_API_KEY:'test-key'},fetchImpl:async url=>{assert.equal(url.searchParams.get('place_id'),'free-analysis-place-id');return {ok:true,json:async()=>({status:'OK',results:[{formatted_address:'11427 Reed Hartman Hwy, Blue Ash, OH 45242, USA',types:['street_address']}]})};}});assert.equal(verified.address,'11427 Reed Hartman Hwy, Blue Ash, OH 45242, USA');});
test('schema mapping is dynamic and missing stage fails closed',()=>{assert.equal(resolveMapping(schema,config,'NEW LEAD (M)').owner,'owner-custom');assert.throws(()=>resolveMapping(schema,config,'Wrong stage'));assert.throws(()=>resolveMapping(schema.filter(f=>f.type!=='person'),config,'NEW LEAD (M)'));});
test('card carries form description, linked page URL, contact, stage, source and escaped notes',()=>{const payload=cardPayload({...lead,message:'<script>bad</script>'},resolveMapping(schema,config,'NEW LEAD (M)'),'contact-id','NEW LEAD (M)');assert.equal(payload['owner-custom'],'contact-id');assert.equal(payload.stage,'NEW LEAD (M)');assert.equal(payload.leadSource,'Website');assert.match(payload.name,/Free Rental Analysis/);assert.ok(payload.description.includes('<strong>Form description:</strong>'));assert.ok(payload.description.includes('completed the Free Rental Analysis request form'));assert.ok(payload.description.includes(`<a href="${lead.pageUrl}">${lead.pageUrl}</a>`));assert.ok(payload.description.includes(lead.pageTitle));assert.ok(payload.description.includes('&lt;script&gt;'));});
test('page context is required and form descriptions cannot be supplied by the browser',()=>{assert.throws(()=>normalizeLead({...lead,pageTitle:''}));assert.throws(()=>normalizeLead({...lead,pageUrl:'/free-rental-analysis'}));const normalized=normalizeLead({...lead,formDescription:'Browser supplied text'});assert.equal('formDescription' in normalized,false);});
test('all general website forms normalize into source-specific lead cards',()=>{
  const cases=[
    {formSource:'For Sale – Free Rental Analysis',address:'123 Main St',pageUrl:'https://example.com/for-sale',description:/browsing EquityTeam properties for sale/},
    {formSource:'Portal Login – Free Rental Analysis',address:'456 Oak St',pageUrl:'https://example.com/portal-logins',description:/Portal Logins page/},
    {formSource:'Rental Match Request',pageUrl:'https://example.com/for-rent',address:'Not provided — Rental Match Request',description:/rental matching their preferences/},
    {formSource:'Contact Us Inquiry',pageUrl:'https://example.com/contact-us',address:'Not provided — Contact Us',description:/general Contact Us form/},
  ];
  for(const item of cases){
    const normalized=normalizeLead({name:'Website Visitor',phone:'513-555-0100',email:'visitor@example.com',address:item.address,formSource:item.formSource,summary:'Submitted details',pageTitle:'EquityTeam website form',pageUrl:item.pageUrl});
    assert.equal(normalized.address,item.address);
    const payload=cardPayload(normalized,resolveMapping(schema,config,'NEW LEAD (M)'),'contact-id','NEW LEAD (M)');
    assert.equal(payload.stage,'NEW LEAD (M)');
    assert.equal(payload.leadSource,'Website');
    assert.match(payload.description,item.description);
    assert.match(payload.description,new RegExp(item.pageUrl.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
  }
});
const reportLead=normalizeLead({firstName:'Example',lastName:'Owner',email:'test@example.com',address:'Unverified entry',placeId:'google-place-id',formSource:'PM Fee ROI Calculator – Email Report',summary:'Annual PM fee: $2,000\nNet ROI: $5,000',pageTitle:'PM Fee ROI Calculator | EquityTeam',pageUrl:'https://example.com/tools/pm-fee-roi'});
test('Google place verification replaces browser address with a verified street address',async()=>{const verified=await verifyGoogleAddress(reportLead,{env:{GOOGLE_MAPS_API_KEY:'test-key'},fetchImpl:async url=>{assert.equal(url.searchParams.get('place_id'),'google-place-id');return {ok:true,json:async()=>({status:'OK',results:[{formatted_address:'11427 Reed Hartman Hwy, Cincinnati, OH 45241, USA',types:['street_address']}]})};}});assert.equal(verified.address,'11427 Reed Hartman Hwy, Cincinnati, OH 45241, USA');});
test('Google verification rejects non-street results',async()=>{await assert.rejects(verifyGoogleAddress(reportLead,{env:{GOOGLE_MAPS_API_KEY:'test-key'},fetchImpl:async()=>({ok:true,json:async()=>({status:'OK',results:[{formatted_address:'Cincinnati, OH, USA',types:['locality']}]})})}));});
test('report email is addressed to the owner and linked to the lead card',()=>{const email=reportEmailPayload(reportLead,'card-id',{APTLY_EMAIL_USER_ID:'user-id',APTLY_EMAIL_CHANNEL_ID:'channel-id'});assert.equal(email.aptletInstanceId,'card-id');assert.equal(email.channelId,'channel-id');assert.deepEqual(email.to,[{value:'test@example.com',name:'Example Owner'}]);assert.equal(email.failOnCreateNewThread,false);assert.ok(email.body.includes('Annual PM fee: $2,000'));});
test('Rent vs. Sell uses the same verified-address and linked-email flow',async()=>{const rentLead=normalizeLead({...reportLead,formSource:'Rent vs. Sell Calculator – Personalized Rental Analysis',summary:'Estimated wealth if rented: $500,000\nEstimated wealth if sold: $450,000',pageTitle:'Rent vs. Sell Calculator | EquityTeam',pageUrl:'https://example.com/tools/rent-vs-sell'});const verified=await verifyGoogleAddress(rentLead,{env:{GOOGLE_MAPS_API_KEY:'test-key'},fetchImpl:async()=>({ok:true,json:async()=>({status:'OK',results:[{formatted_address:'123 Main St, Cincinnati, OH 45202, USA',types:['street_address']}]})})});assert.equal(verified.address,'123 Main St, Cincinnati, OH 45202, USA');const email=reportEmailPayload(verified,'rent-card',{APTLY_EMAIL_USER_ID:'user-id',APTLY_EMAIL_CHANNEL_ID:'channel-id'});assert.equal(email.aptletInstanceId,'rent-card');assert.match(email.subject,/Rent vs\. Sell report/);assert.match(email.body,/Your Rent vs\. Sell Report/);assert.match(email.body,/financial or tax advice/);});
const evictionLead=normalizeLead({firstName:'Example',lastName:'Owner',phone:'(513) 555-0199',email:'owner@example.com',message:'I would like to discuss tenant screening.',summary:'Estimated total eviction cost: $10,950',formSource:'Eviction Cost Calculator – Consultation Request',pageTitle:'Eviction Cost Calculator | EquityTeam',pageUrl:'https://example.com/tools/eviction-cost'});
test('eviction consultation validates contact details without asking for a property address',()=>{assert.equal(evictionLead.name,'Example Owner');assert.equal(evictionLead.address,'Not provided — Eviction Cost Calculator');assert.throws(()=>normalizeLead({...evictionLead,phone:'12'}));assert.throws(()=>normalizeLead({...evictionLead,message:''}));});
test('eviction lead records the calculator source, contact details, summary, and mapped fields',()=>{const mapping=resolveMapping(schema,config,'NEW LEAD (M)','Eviction Cost Calculator');const payload=cardPayload(evictionLead,mapping,'contact-id','NEW LEAD (M)');assert.equal(payload.stage,'NEW LEAD (M)');assert.equal(payload.leadSource,'Website');assert.equal(payload.trackingPhone,'(513) 555-0199');assert.equal(payload.trackingEmail,'owner@example.com');assert.match(payload.name,/Eviction Cost Calculator/);assert.match(payload.description,/schedule a conversation/);assert.match(payload.description,/\(513\) 555-0199/);assert.match(payload.description,/Estimated total eviction cost/);assert.match(payload.description,/tools\/eviction-cost/);});
const exchangeLead=normalizeLead({firstName:'Exchange',lastName:'Owner',phone:'513-555-0123',email:'exchange@example.com',address:'Unverified entry',placeId:'google-place-id',message:'I want to discuss an upcoming exchange.',summary:'Estimated tax deferred: $91,000',formSource:'1031 Exchange Calculator – Consultation Request',pageTitle:'1031 Exchange Calculator | EquityTeam',pageUrl:'https://example.com/tools/1031-exchange'});
test('1031 consultation requires a verified property address and records its calculator source',async()=>{assert.throws(()=>normalizeLead({...exchangeLead,placeId:''}));const verified=await verifyGoogleAddress(exchangeLead,{env:{GOOGLE_MAPS_API_KEY:'test-key'},fetchImpl:async()=>({ok:true,json:async()=>({status:'OK',results:[{formatted_address:'456 Investment Way, Cincinnati, OH 45202, USA',types:['street_address']}]})})});assert.equal(verified.address,'456 Investment Way, Cincinnati, OH 45202, USA');const payload=cardPayload(verified,resolveMapping(schema,config,'NEW LEAD (M)','1031 Exchange'),'contact-id','NEW LEAD (M)');assert.equal(payload.stage,'NEW LEAD (M)');assert.equal(payload.leadSource,'Website');assert.match(payload.name,/1031 Exchange Calculator/);assert.match(payload.description,/1031 Exchange Calculator/);assert.match(payload.description,/Estimated tax deferred/);assert.match(payload.description,/tools\/1031-exchange/);});
const vacancyLead=normalizeLead({firstName:'Vacancy',lastName:'Owner',phone:'513-555-0144',email:'vacancy@example.com',address:'Unverified entry',placeId:'vacancy-place-id',message:'Please help me reduce vacancy.',summary:'Estimated annual savings with professional management: $4,200',formSource:'Vacancy Cost Calculator – Consultation Request',pageTitle:'Vacancy Cost Calculator | EquityTeam',pageUrl:'https://example.com/tools/vacancy-cost'});
test('vacancy consultation requires a verified address and creates calculator-specific card details',async()=>{const verified=await verifyGoogleAddress(vacancyLead,{env:{GOOGLE_MAPS_API_KEY:'test-key'},fetchImpl:async()=>({ok:true,json:async()=>({status:'OK',results:[{formatted_address:'789 Rental Ave, Cincinnati, OH 45208, USA',types:['street_address']}]})})});const payload=cardPayload(verified,resolveMapping(schema,config,'NEW LEAD (M)','Vacancy Cost'),'contact-id','NEW LEAD (M)');assert.equal(payload.stage,'NEW LEAD (M)');assert.equal(payload.leadSource,'Website');assert.equal(payload.trackingPhone,'513-555-0144');assert.match(payload.name,/Vacancy Cost Calculator/);assert.match(payload.description,/reducing vacancy/);assert.match(payload.description,/Estimated annual savings/);assert.match(payload.description,/tools\/vacancy-cost/);});
const strLtrLead=normalizeLead({firstName:'Rental',lastName:'Owner',email:'rental@example.com',address:'Unverified entry',placeId:'str-ltr-place-id',summary:'Recommended strategy: Long-term rental\nLTR annual net income: $17,000',formSource:'STR vs. LTR Calculator – Email Report',pageTitle:'STR vs. LTR Calculator | EquityTeam',pageUrl:'https://example.com/tools/str-vs-ltr'});
test('STR vs. LTR report verifies the rental address and creates a linked email payload',async()=>{const verified=await verifyGoogleAddress(strLtrLead,{env:{GOOGLE_MAPS_API_KEY:'test-key'},fetchImpl:async()=>({ok:true,json:async()=>({status:'OK',results:[{formatted_address:'321 Rental Strategy Rd, Cincinnati, OH 45209, USA',types:['street_address']}]})})});const payload=cardPayload(verified,resolveMapping(schema,config,'NEW LEAD (M)','STR vs. LTR'),'contact-id','NEW LEAD (M)');assert.equal(payload.stage,'NEW LEAD (M)');assert.match(payload.description,/STR vs\. LTR Calculator/);assert.match(payload.description,/Recommended strategy/);assert.match(payload.description,/tools\/str-vs-ltr/);const email=reportEmailPayload(verified,'str-ltr-card',{APTLY_EMAIL_USER_ID:'user-id',APTLY_EMAIL_CHANNEL_ID:'channel-id'});assert.equal(email.aptletInstanceId,'str-ltr-card');assert.match(email.subject,/STR vs\. LTR report/);assert.match(email.body,/Your STR vs\. LTR Rental Strategy Report/);assert.match(email.body,/Short-term rental rules vary/);});
test('realtor referral creates owner prospect and agent contacts attached to an Agent Referral card',async()=>{
 const referral=normalizeLead({firstName:'Referred',lastName:'Owner',phone:'513-555-0101',email:'owner@example.com',address:'123 Referral Ave, Cincinnati, OH',message:'Owns a single-family rental.',referrerFirstName:'Rita',referrerLastName:'Agent',referrerPhone:'513-555-0102',referrerEmail:'rita@example.com',formSource:'Realtor Referral Program',pageTitle:'Realtor Referral Program | EquityTeam',pageUrl:'https://example.com/realtor-referral-program'});
 const referralConfig={data:{fields:[{uuid:'stage',data:[{label:'NEW LEAD (M)'}]},{uuid:'leadSource',data:[{label:'Website'},{label:'Agent Referral'}]}]}};
 const calls=[];let contactCount=0;
 const result=await createOwnerLead(referral,{env:{APTLY_API_TOKEN:'test-only',APTLY_OWNER_LEADS_BOARD_ID:'board-id',APTLY_OWNER_LEADS_STAGE:'NEW LEAD (M)'},fetchImpl:async(url,options)=>{calls.push({url,options});if(url.includes('/schema/')) return {ok:true,json:async()=>schema};if(url.endsWith('/configuration')) return {ok:true,json:async()=>referralConfig};if(url.endsWith('/contacts')) return {ok:true,json:async()=>({_id:++contactCount===1?'owner-contact':'agent-contact'})};return {ok:true,json:async()=>({data:{_id:'referral-card'}})};}});
 const contacts=calls.filter(call=>call.url.endsWith('/contacts')).map(call=>JSON.parse(call.options.body));
 const card=JSON.parse(calls.find(call=>call.url.endsWith('/board/board-id')).options.body);
 assert.equal(contacts[0].contactType,'Owner Prospect');assert.equal(contacts[1].contactType,'Agents');
 assert.equal(card['owner-custom'],'owner-contact');assert.deepEqual(card.relatedContacts,['agent-contact']);assert.equal(card.leadSource,'Agent Referral');assert.equal(card.stage,'NEW LEAD (M)');assert.equal(card.address.address,'123 Referral Ave, Cincinnati, OH');assert.match(card.description,/Rita Agent/);assert.match(card.description,/Owns a single-family rental/);assert.equal(result.referrerContactId,'agent-contact');
});
test('realtor referral accepts an omitted property address but requires both contacts',()=>{
 const base={firstName:'Referred',lastName:'Owner',phone:'513-555-0101',email:'owner@example.com',referrerFirstName:'Rita',referrerLastName:'Agent',referrerPhone:'513-555-0102',referrerEmail:'rita@example.com',formSource:'Realtor Referral Program',pageTitle:'Realtor Referral Program | EquityTeam',pageUrl:'https://example.com/realtor-referral-program'};
 assert.equal(normalizeLead(base).address,'Not provided — Realtor Referral Program');
 assert.throws(()=>normalizeLead({...base,referrerEmail:''}));
});
test('server flow creates contact then mapped card without exposing credentials',async()=>{
 const calls=[];await createOwnerLead(lead,{env:{APTLY_API_TOKEN:'test-only',APTLY_OWNER_LEADS_BOARD_ID:'board-id',APTLY_OWNER_LEADS_STAGE:'NEW LEAD (M)'},fetchImpl:async(url,options)=>{calls.push({url,options});const data=url.includes('/schema/')?schema:url.endsWith('/configuration')?config:url.endsWith('/contacts')?{_id:'contact-id'}:{data:{_id:'card-id'}};return {ok:true,json:async()=>data};}});
 const posts=calls.filter(c=>c.options.method==='POST');assert.equal(posts.length,2);assert.equal(JSON.parse(posts[0].options.body).contactType,'Owner');assert.equal(JSON.parse(posts[1].options.body).stage,'NEW LEAD (M)');assert.ok(!posts[1].options.body.includes('test-only'));
});
test('upstream failure stops submission',async()=>{await assert.rejects(createOwnerLead(lead,{env:{APTLY_API_TOKEN:'test',APTLY_OWNER_LEADS_BOARD_ID:'b',APTLY_OWNER_LEADS_STAGE:'NEW LEAD (M)'},fetchImpl:async()=>({ok:false,status:403})}));});
test('PM ROI lead creates the card before sending a linked email',async()=>{const calls=[];const env={APTLY_API_TOKEN:'test-only',APTLY_OWNER_LEADS_BOARD_ID:'board-id',APTLY_OWNER_LEADS_STAGE:'NEW LEAD (M)',APTLY_EMAIL_USER_ID:'user-id',APTLY_EMAIL_CHANNEL_ID:'channel-id'};const result=await createOwnerLead(reportLead,{env,fetchImpl:async(url,options)=>{calls.push({url,options});const data=url.includes('/schema/')?schema:url.endsWith('/configuration')?config:url.endsWith('/contacts')?{_id:'contact-id'}:url.endsWith('/email/send')?{data:{sent:true}}:{data:{_id:'card-id'}};return {ok:true,json:async()=>data};}});const emailCall=calls.find(call=>call.url.endsWith('/email/send'));assert.equal(result.emailSent,true);assert.ok(emailCall);assert.equal(JSON.parse(emailCall.options.body).aptletInstanceId,'card-id');assert.ok(calls.findIndex(call=>call.url.endsWith('/email/send'))>calls.findIndex(call=>call.url.endsWith('/board/board-id')));});
test('eviction flow stores the phone on the contact and creates a NEW LEAD (M) card',async()=>{const calls=[];await createOwnerLead(evictionLead,{env:{APTLY_API_TOKEN:'test-only',APTLY_OWNER_LEADS_BOARD_ID:'board-id',APTLY_OWNER_LEADS_STAGE:'NEW LEAD (M)'},fetchImpl:async(url,options)=>{calls.push({url,options});const data=url.includes('/schema/')?schema:url.endsWith('/configuration')?config:url.endsWith('/contacts')?{_id:'contact-id'}:{data:{_id:'card-id'}};return {ok:true,json:async()=>data};}});const contact=JSON.parse(calls.find(call=>call.url.endsWith('/contacts')).options.body);const card=JSON.parse(calls.find(call=>call.url.endsWith('/board/board-id')).options.body);assert.deepEqual(contact.phone,[{number:'(513) 555-0199',type:'mobile'}]);assert.equal(card.stage,'NEW LEAD (M)');assert.equal(card.trackingPhone,'(513) 555-0199');assert.match(card.description,/Eviction Cost Calculator/);});
