// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pricing-redesign/DiffTable.tsx": () => import("../components/mockups/pricing-redesign/DiffTable.tsx"),
  "./components/mockups/pricing-redesign/Differences.tsx": () => import("../components/mockups/pricing-redesign/Differences.tsx"),
  "./components/mockups/pricing-redesign/FeeCards.tsx": () => import("../components/mockups/pricing-redesign/FeeCards.tsx"),
  "./components/mockups/pricing-redesign/TwoColumn.tsx": () => import("../components/mockups/pricing-redesign/TwoColumn.tsx"),
  "./components/mockups/pricing-variants/ComparisonTable.tsx": () => import("../components/mockups/pricing-variants/ComparisonTable.tsx"),
  "./components/mockups/pricing-variants/FeatureLed.tsx": () => import("../components/mockups/pricing-variants/FeatureLed.tsx"),
  "./components/mockups/pricing-variants/TieredCards.tsx": () => import("../components/mockups/pricing-variants/TieredCards.tsx")
};
